# Generated by Django 4.2.3 on 2023-10-18 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeySetup',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('key1_private_encoded', models.CharField(max_length=4096)),
                ('key1_public', models.CharField(max_length=2056)),
                ('key2_private', models.CharField(max_length=4096)),
                ('key2_public', models.CharField(max_length=2056)),
                ('totp_key', models.CharField(max_length=2056)),
                ('active', models.BooleanField(default=False)),
                ('local_secret', models.CharField(max_length=685)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=328)),
                ('url', models.CharField(max_length=328)),
                ('username', models.CharField(max_length=1369)),
                ('password', models.CharField(max_length=1369)),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'id'], name='compass_pas_user_id_6fb974_idx')],
            },
        ),
    ]
