# Generated by Django 4.2.3 on 2023-10-18 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keysetup',
            name='key1_private_encoded',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='keysetup',
            name='key1_public',
            field=models.CharField(max_length=2056, null=True),
        ),
        migrations.AlterField(
            model_name='keysetup',
            name='local_secret',
            field=models.CharField(max_length=685, null=True),
        ),
        migrations.AlterField(
            model_name='keysetup',
            name='totp_key',
            field=models.CharField(max_length=2056, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='name',
            field=models.CharField(max_length=328, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='url',
            field=models.CharField(max_length=328, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.CharField(max_length=1369, null=True),
        ),
    ]
